// <auto-generated />
using System;
using ICEHOTT.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICEHOTT.Persistence.Migrations
{
    [DbContext(typeof(ICEHOTTDbContext))]
    [Migration("20260925204435_Phase45ToolQuotas")]
    partial class Phase45ToolQuotas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICEHOTT.Domain.Agents.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WorkspaceId", "UpdatedAtUtc");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Agents.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "ConversationId", "CreatedAtUtc");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Agents.ConversationMessageCitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "MessageId");

                    b.ToTable("conversation_message_citations", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.EmbeddingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<string>("DistanceMetric")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("IndexVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Normalization")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Provider", "Model", "Version", "IndexVersion")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "IX_embedding_profiles_Active")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex(new[] { "Status" }, "IX_embedding_profiles_Building")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Building'");

                    b.ToTable("embedding_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f36a640-0d25-4a76-9d0d-640000000001"),
                            ActivatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dimensions = 64,
                            DistanceMetric = "cosine",
                            IndexVersion = 1,
                            Key = "local-deterministic-64-v1",
                            Model = "deterministic-64d",
                            Normalization = "unit",
                            Provider = "icehott-ai-runtime",
                            Status = "Active",
                            Version = "1"
                        });
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "WorkspaceId");

                    b.HasIndex("DocumentId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "DocumentId", "Ordinal");

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.KnowledgeProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "WorkspaceId")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAtUtc");

                    b.HasIndex("Status", "LockedUntilUtc");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc");

                    b.ToTable("knowledge_processing_jobs", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.RagEvaluationEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AnswerRelevance")
                        .HasColumnType("double precision");

                    b.Property<double>("CitationCorrectness")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ContextPrecision")
                        .HasColumnType("double precision");

                    b.Property<double?>("ContextRecall")
                        .HasColumnType("double precision");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmbeddingProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvaluationKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("Faithfulness")
                        .HasColumnType("double precision");

                    b.Property<double?>("Groundedness")
                        .HasColumnType("double precision");

                    b.Property<double>("HitRateAtK")
                        .HasColumnType("double precision");

                    b.Property<int>("IndexVersion")
                        .HasColumnType("integer");

                    b.Property<double>("MeanPrecisionAtK")
                        .HasColumnType("double precision");

                    b.Property<double>("MeanRecallAtK")
                        .HasColumnType("double precision");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RunnerVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("TenantLeakageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingProfileId", "DatasetVersion", "EvaluationKind", "CompletedAtUtc");

                    b.ToTable("rag_evaluation_evidence", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Security.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("PolicyMaxArgumentLength")
                        .HasColumnType("integer");

                    b.Property<int?>("PolicyMinimumApproverRole")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyMinimumRequesterRole")
                        .HasColumnType("integer");

                    b.Property<bool>("PolicyRequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("WorkspaceId", "RequestedAtUtc");

                    b.HasIndex("WorkspaceId", "ToolName", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("tool_executions", null, t =>
                        {
                            t.HasCheckConstraint("CK_tool_executions_PolicyApprover", "(\"PolicyRequiresApproval\" AND \"PolicyMinimumApproverRole\" IS NOT NULL AND \"PolicyMinimumApproverRole\" BETWEEN 2 AND 3) OR (NOT \"PolicyRequiresApproval\" AND \"PolicyMinimumApproverRole\" IS NULL)");

                            t.HasCheckConstraint("CK_tool_executions_PolicyMinimumRequesterRole", "\"PolicyMinimumRequesterRole\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_tool_executions_PolicyVersion", "\"PolicyVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolExecutionAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ExecutionId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "ExecutionId", "OccurredAtUtc");

                    b.ToTable("tool_execution_audit_events", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolPolicy", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxArgumentLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumApproverRole")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumRequesterRole")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("WorkspaceId", "ToolName");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("tool_policies", null, t =>
                        {
                            t.HasCheckConstraint("CK_tool_policies_MaxArgumentLength", "\"MaxArgumentLength\" IS NULL OR \"MaxArgumentLength\" > 0");

                            t.HasCheckConstraint("CK_tool_policies_MinimumApproverRole", "\"MinimumApproverRole\" IS NULL OR \"MinimumApproverRole\" BETWEEN 2 AND 3");

                            t.HasCheckConstraint("CK_tool_policies_MinimumRequesterRole", "\"MinimumRequesterRole\" IS NULL OR \"MinimumRequesterRole\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_tool_policies_Version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolPolicyAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewPolicyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousPolicyJson")
                        .HasColumnType("text");

                    b.Property<int>("PreviousVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("WorkspaceId", "ToolName", "NewVersion")
                        .IsUnique();

                    b.ToTable("tool_policy_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_tool_policy_audit_events_Versions", "\"NewVersion\" = \"PreviousVersion\" + 1");
                        });
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolQuotaCounter", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<long>("WindowStartUnixSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("WorkspaceId", "ToolName");

                    b.ToTable("tool_quota_counters", null, t =>
                        {
                            t.HasCheckConstraint("CK_tool_quota_counters_Count", "\"Count\" >= 0");

                            t.HasCheckConstraint("CK_tool_quota_counters_WindowStartUnixSeconds", "\"WindowStartUnixSeconds\" >= 0");
                        });
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.WorkspaceAuditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ToolExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ToolExecutionId")
                        .IsUnique();

                    b.HasIndex("ToolExecutionId", "WorkspaceId");

                    b.ToTable("workspace_audit_notes", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Workspaces.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("WorkspaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("workspace_memberships", (string)null);
                });

            modelBuilder.Entity("ICEHOTT.Domain.Agents.Conversation", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Agents.ConversationMessage", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Agents.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Agents.ConversationMessageCitation", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Agents.ConversationMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.KnowledgeChunk", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Knowledge.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.KnowledgeDocument", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.KnowledgeProcessingJob", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Knowledge.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Knowledge.RagEvaluationEvidence", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Knowledge.EmbeddingProfile", null)
                        .WithMany()
                        .HasForeignKey("EmbeddingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Security.RefreshSession", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolExecution", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolExecutionAuditEvent", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICEHOTT.Domain.Tools.ToolExecution", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolPolicy", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolPolicyAuditEvent", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.ToolQuotaCounter", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Tools.WorkspaceAuditNote", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEHOTT.Domain.Tools.ToolExecution", null)
                        .WithMany()
                        .HasForeignKey("ToolExecutionId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ICEHOTT.Domain.Workspaces.WorkspaceMembership", b =>
                {
                    b.HasOne("ICEHOTT.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICEHOTT.Domain.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });
#pragma warning restore 612, 618
        }
    }
}
